---
name: Test Hypha
on:
  push:
    branches:
    - develop
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Compile libhypha
      run: |
        meson setup build --reconfigure
        ninja -C build
    - name: Run Tests
      run: |
        meson test -C build --print-errorlogs
