---
name: Render and Commit VHS Tapes
on:
  push:
    branches:
    - develop
    paths:
    - assets/*.tape
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  vhs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/arcadia-de/hypha/hypha-build-env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install VHS and Dependencies
      run: |
        apt-get update
        apt-get install -y chromium-browser ffmpeg
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://charm.sh | gpg --dearmor -o /etc/apt/keyrings/charm.gpg
        echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://charm.sh * *" | tee /etc/apt/sources.list.d/charm.list
        apt-get update && apt-get install vhs
    - name: Compile libhypha
      run: |
        VERSION="${{ needs.release-please.outputs.version }}"
        if [ -z "$VERSION" ]; then
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
        fi

        meson setup build --reconfigure
        ninja -C build
    - name: Compile Hypha
      run: |
        export CGO_ENABLED=1
        export PKG_CONFIG_PATH="$(pwd)/build/meson-uninstalled:$PKG_CONFIG_PATH"

        VERSION="${{ needs.release-please.outputs.version }}"
        if [ -z "$VERSION" ]; then
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
        fi

        go build -ldflags="-X main.Version=$VERSION -linkmode=external -s -w -extldflags=-Wl,--gc-sections" \
          -o hypha \
          cmd/hypha/main.go
    - name: Render Tapes
      run: |
        for tape in assets/*.tape; do
          [ -e "$tape" ] || continue
          echo "🎬 Processing: $tape"
          vhs "$tape"
        done
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@://github.com"
        git add assets/
        if git diff-index --quiet HEAD; then
          echo "No changes to commit."
        else
          git commit -m "chore: auto-render updated VHS tape [skip ci]"
          git push
        fi
